// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20240704183427_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15df8273-f05f-4a9c-8675-477769409a2b"),
                            Content = "Ksdfn, rprprprmg tmerptm mr trlntrltm, rptmr.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("54c8eb46-6c86-43e1-aedb-f8093fd29382"),
                            Content = "Jspsejfpe lfnrtl pmrprmp me ptrtneptp trt. Kmetertoerton elnerl rm.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("3af5a334-3de0-4490-8f42-0bbeb63b346e"),
                            Content = "Ojdoffornfo fnro forjnoerntorj, owenfron, prnrpr.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
